#pragma once

#include "create_vertex_arrays.hpp"
#include "bind_vertex_array.hpp"
#include "delete_vertex_arrays.hpp"
#include "disable_vertex_array_attrib.hpp"
#include "draw_arrays_instanced.hpp"
#include "draw_arrays.hpp"
#include "draw_elements.hpp"
#include "draw_elements_instanced.hpp"
#include "enable_vertex_array_attrib.hpp"
#include "vertex_array_attrib_binding.hpp"
#include "vertex_array_attrib_divisor.hpp"
#include "vertex_array_attrib_format.hpp"
#include "vertex_array_element_buffer.hpp"
#include "vertex_array_vertex_buffer.hpp"
